---
- id: buf-check-lint
  description: "Runs buf check lint. Requires buf to be installed separately"
  name: buf-check-lint
  entry: "protobuf/buf-check-lint.sh"
  types:
    - proto
  language: script
  pass_filenames: false
- id: buf-check-breaking
  description: "Runs buf breaking. Requires buf to be installed separately"
  name: buf-check-breaking
  entry: "protobuf/buf-check-breaking.sh"
  types:
    - proto
  language: script
  pass_filenames: false
- id: golint
  description: "Runs golint. Requires it to be installed separately"
  name: go lint
  entry: "golang/golint.sh"
  types:
    - go
  language: script
- id: go-mod-tidy
  description: "Runs go mod tidy. Requires go to be installed separately"
  name: go-mod-tidy
  entry: "golang/go-mod-tidy.sh"
  types:
    - go
  language: script
  pass_filenames: false
- id: revive
  description: "Runs revive for the current project"
  name: revive
  entry: "golang/revive.sh"
  types:
    - go
  language: script
  pass_filenames: false
- id: shellcheck
  description: "Run shellcheck. Requires shellcheck to be installed separately"
  name: shellcheck
  entry: "shell/shellcheck.sh"
  types:
    - shell
  language: script
- id: make
  description: "Run an arbitrary make target"
  name: make
  entry: "make/make.sh"
  always_run: true
  language: script
  pass_filenames: false
